# Generated by Django 5.0 on 2023-12-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectEase_app', '0007_alter_list_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
